### ISSUE TITLE
Custom SSH Port

### ISSUE THREAD

**Issue by victorehp17** [fortinet-solutions-cse/40ansible#14]
Hi,
Great module, i'm really enjoying it!
Would it be possible to add support for custom SSH ports (non 22)?

**Comment by mamunozgonzalez** [comment]
The new HTTPAPI plugin that is already developed for FortiOS already supports custom ports as it uses Ansible inventory. Localhost connection will be deprecated soon according to Ansible roadmap.

HTTPAPI will be submitted for review shortly in the next days and hopefully will be released soon.

**Comment by mamunozgonzalez** [comment]
Anyway, if you want to use a different port with the current localhost connection just add it after the host ip, using a colon:

```- hosts: localhost
  vars:
   host: "192.168.122.40:450"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
```
