### ISSUE TITLE
fortios_webfilter library without webfilter_profile

### ISSUE THREAD

**Issue by asilnov** [fortinet-solutions-cse/40ansible#18]
Guys, thank you very much for the libs!
I have not found any info about webfilter_profile feature in fortios_webfilter.
Would you add this feature to master?

**Comment by mamunozgonzalez** [comment]
Hi @asilnov,
 At the moment webfilter profile is not included. It will come in the future, together with other modules to handle all fortigate features. Fortigate has many tables (even for webfilter feature) and it will take some time to cover all of them.
Thanks for your feedback!

**Comment by mamunozgonzalez** [comment]
Hi @asilnov ,
 I have uploaded a new module to handle webfilter profiles. Still in beta testing but it can be used already to do some stuff. It will be proposed to Ansible repo shortly thus it may suffer some modifications.

https://github.com/fortinet-solutions-cse/40ansible/blob/master/library/fortios_webfilter_profile.py
