### ISSUE TITLE
Upload license to multiple fortigates

### ISSUE THREAD

**Issue by bruccoo3000** [fortinet-solutions-cse/40ansible#21]
Hello,

Wanted to know if it is possible to load multiple licenses to multiple fortigates using the fortigate_upload_license.yml playbook?

Say I have a folder of licenses and wanted to deploy the licenses across multiple VMs.

Any ideas would be great.

Thanks

**Comment by mamunozgonzalez** [comment]
HI @bruccoo3000 ,
 yes it is possible. You can place a call to fortiosconfig multiple times in the same playbook. This example works:

- hosts: localhost
  tasks:
  - name: Upload license
    fortiosconfig:
     config: "system vmlicense upload"
     action: "upload"
     host:  "192.168.122.40"
     username: "admin"
     password: ""
     vdom:  "global"
     https: False
     config_parameters:
      filename: "license_file.lic"
  - name: Upload license second fortigate
    fortiosconfig:
     config: "system vmlicense upload"
     action: "upload"
     host:  "192.168.122.41"
     username: "admin"
     password: ""
     vdom:  "global"
     https: False
     config_parameters:
      filename: "license_file2.lic"

Hope that helps,
Miguel Ángel.

**Comment by mamunozgonzalez** [comment]
I have added a new working example for this case:

https://github.com/fortinet-solutions-cse/40ansible/blob/master/examples/fortigate_upload_license_multiple_fortigates.yml

Miguel Ángel.

**Comment by mamunozgonzalez** [comment]
Also, for the sake of code simplicity you can try with 'items', following this example:

https://docs.ansible.com/ansible/2.6/plugins/lookup/items.html

Let us know if you want to implement it like this or more help is needed.

**Comment by bruccoo3000** [comment]
Awesome!

I'm spinning up different FortiOS VM versions today (5.4, 5.6 and 6.0, all latest in code train) and will let you know.

**Comment by mamunozgonzalez** [comment]
Apparently everything is correct. I have also a similar setup with licenses in other dirs and it works fine. From the logs it seems that the ansible process can't find the file, probably due to permissions or a different user running the ansible process.
Who is the user running the ansible-playbook command? 
Can you also post the command used to run the playbook?
And just for a quick and simple test, could you make the license and its dir fully open to everyone (chmod +644 xxx.lic)?

**Comment by bruccoo3000** [comment]
So, here's what I have:
The user is 'ansible'
[ansible@ansible ~]$ whoami
ansible

The user 'ansible' is running the playbook using the following command:
ansible-playbook fortigate_upload_license1.yml > fortilicense.out

Changed the permissions as suggested and no change.

**Comment by mamunozgonzalez** [comment]
Please run an additional test: put your license file in the same dir where your ansible module is. And run your playbook from that same directory. 
Can you post here your operating system and version? (cat /etc/*release*)
Also if you run some software like AppArmor/SELinux or similar thing?
If that does not work, would you be available for a call with remote assistance?

**Comment by bruccoo3000** [comment]
OK, good news!

Moved the licenses to the folder of my playbook worked!  All devices are now licensed.  But I would still like to use a path (absolute or relative) in order to have better management of the licenses.

Does this mean that the "filename" key can't use a path?  Is there another option to use instead?  I tried replacing "filename" with "dest" but that didn't seem to work either.

Here's the requested information:
Operating System and Version:
[ansible@ansible etc]$ more centos-release
CentOS Linux release 7.5.1804 (Core)
[ansible@ansible etc]$ more centos-release-upstream
Derived from Red Hat Enterprise Linux 7.5 (Source)

Selinux status:
[ansible@ansible /]$ sestatus -v
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31

Process contexts:
Current context:                unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
Init context:                   system_u:system_r:init_t:s0

File contexts:
Controlling terminal:           unconfined_u:object_r:user_devpts_t:s0
/etc/passwd                     system_u:object_r:passwd_file_t:s0
/etc/shadow                     system_u:object_r:shadow_t:s0
/bin/bash                       system_u:object_r:shell_exec_t:s0
/bin/login                      system_u:object_r:login_exec_t:s0
/bin/sh                         system_u:object_r:bin_t:s0 -> system_u:object_r:shell_exec_t:s0
/sbin/agetty                    system_u:object_r:getty_exec_t:s0
/sbin/init                      system_u:object_r:bin_t:s0 -> system_u:object_r:init_exec_t:s0
/usr/sbin/sshd                  system_u:object_r:sshd_exec_t:s0
/lib/libc.so.6                  system_u:object_r:lib_t:s0 -> system_u:object_r:lib_t:s0
/lib/ld-linux.so.2              system_u:object_r:lib_t:s0 -> system_u:object_r:ld_so_t:s0

I can also try disabling selinux to see if that makes a difference.

I am also able to work with you remotely as well.

Thanks again!

**Comment by bruccoo3000** [comment]
Also, this means that this works on the tested versions of 5.4, 5.6 and 6.0 FortiVMs.  Now, I would definitely like to work on the list function as that may be a more elegant method.

**Comment by mamunozgonzalez** [comment]
Cool!! Yes, please disable SElinux and try again. Please use an absolute path. 
That ansible module can access files in other paths. I have tested recently this path /home/magonzalez/license.lic and had no issues.

**Comment by bruccoo3000** [comment]
Nice!  Ok, updated the system, updated my pathing and disabled SElinux.
Working!

Thanks for the help on this, do you think this would be the best method to deploy licenses for 1000 VMs or would a list method be better?  Picking your brain on this as someone who knows what they're doing :)

**Comment by mamunozgonzalez** [comment]
Great to read that!!!
Regarding provisioning 1000 VMs, using 'items' only would probably give similar results in terms of speed (but code is more elegant and simplified). 

Can you try with asynchronous tasks? With this Ansible feature you will execute the tasks and will not wait for each one to be fully finished. I guess we should gain some speed. This feature is compatible with 'items' so you can have your playbook faster and really simplified.
There are some examples and guides in:

https://docs.ansible.com/ansible/2.6/user_guide/playbooks_async.html
http://toroid.org/ansible-parallel-dispatch

(Probably it will be enough to add 'async: XX' and 'poll:0' right below 'name'  in the playbook, but I guess you can try different approaches)

If that does not work there is another possibility consisting on developing a small application (python/java/c++) that accesses FGT REST api directly and issues simultaneously 1000 independent requests using multiple threads. That one can be very fast but requires more time to develop.

Hope that helps.

**Comment by thomnico** [comment]
Hello bruccoo3000,

If you have more than 1000 VM I strongly encourage you to reach your Fortinet rep and check the benefit or Fortimanager (which can also be managed with Ansible) and the metering pay as you grow licensing model.

Of course, you are free to redo all that with our Ansible modules. Licensing is done very infrequently so the speed should not be an issue.

**Comment by bruccoo3000** [comment]
Hey all,

Thanks again for the help and ideas as how to proceed.

Our fortinet rep was able to somewhat help with part of our process but the fortimanager is a no go for this environment.

I like the async idea as there are more functions I need to add but the licensing was a huge sticking point.
