### ISSUE TITLE
Add the wait for connectivity to the login call and ssh one (in the lib)

### ISSUE THREAD

**Issue by thomnico** [fortinet-solutions-cse/40ansible#3]

**Comment by mamunozgonzalez** [comment]
The new HTTPAPI plugin that is already developed for FortiOS handles all the connectivity issues, including timeouts and other variables, as it uses Ansible inventory. Localhost connection will be deprecated soon according to Ansible roadmap.

HTTPAPI will be submitted for review shortly in the next days and hopefully will be released soon.
