### ISSUE TITLE
Backup_path for config backup

### ISSUE THREAD

**Issue by ciscler** [fortinet-solutions-cse/40ansible#34]
Hi all,

is there a way to define the path where ansible is storing the Fortigate Configuration files?

best Regards,

**Comment by mamunozgonzalez** [comment]
Hi @ciscler,
You can use the filename attribute as shown below to specify a full path. https://github.com/fortinet-solutions-cse/40ansible/blob/f12b834e4a873828ed5c2812cd234c9477d31270/examples/fortigate_backup_config.yml#L18
