### ISSUE TITLE
error message when using the ssh action

### ISSUE THREAD

**Issue by caibitim** [fortinet-solutions-cse/40ansible#36]
I'm trying to run some command through ssh, and It looks like I get the correct result. However, when I turn on the debug from ansible it says:

err": "<paramiko.ChannelFile from <paramiko.Channel 0 (closed) -> <paramiko.Transport at 0xb89cd860 (unconnected)>>>

is this err is expeteced since it's just the paramiko saying the connection is closed or it's a bug?

**Comment by mamunozgonzalez** [comment]
I can confirm this is a bug but It is originated in FortiOSAPI (https://github.com/fortinet-solutions-cse/fortiosapi) . I'll create a PR to fix it in that repository and post the link here to follow up.

**Comment by mamunozgonzalez** [comment]
PR created: https://github.com/fortinet-solutions-cse/fortiosapi/pull/40
