### ISSUE TITLE
"Unsupported parameters for (fortios_config) module:

### ISSUE THREAD

**Issue by jerrytoh123** [fortinet-solutions-cse/40ansible#43]
Hey man! thanks for the great work to compile the ansible module for Fortigate FW!

I tried to run fortigate_mix.yml and met with the following errors:
"msg": "Unsupported parameters for (fortios_config) module: action,config,config_parameters,https Supported parameters include: backup,backup_filename,backup_path,config_file,file_mode,filter,host,password,src,timeout,username,vdom"
}
Please advise on how can I resolve this errors as im new to ansible. 
Thank you in advance!
Cheers!

**Comment by mamunozgonzalez** [comment]
Hi @jerrytoh123,
 sure, it's a pleasure. I haven't looked into details but it looks like you are using forios_config  and not fortiosconfig (the module stored in library/ in this repo). fortigate_mix.yml is intended to run with fortiosconfig (and not fortios_config which is an old module).

Just do: declare -x ANSIBLE_LIBRARY=(library dir of this repo) and re-run fortigate_mix.yml as it is in this repo.

**Comment by jerrytoh123** [comment]
Hey man sorry to trouble you again, I declare the ansible_library but i was met with "MODULE FAILURE" errors when i tried running fortigate_mix.yml, following is the -vvv report:
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jerry
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1559804567.81-26199305813774 `" && echo ansible-tmp-1559804567.81-26199305813774="` echo /root/.ansible/tmp/ansible-tmp-1559804567.81-26199305813774 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp8uEmFG TO /root/.ansible/tmp/ansible-tmp-1559804567.81-26199305813774/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1559804567.81-26199305813774/ /root/.ansible/tmp/ansible-tmp-1559804567.81-26199305813774/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1559804567.81-26199305813774/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1559804567.81-26199305813774/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Set static route on the fortigate] **********************************************
task path: /home/jerry/40ansible/examples/fortigate_mix.yml:11
Using module file /home/jerry/40ansible/examples/fortiosconfig.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jerry
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1559804568.97-125703572820944 `" && echo ansible-tmp-1559804568.97-125703572820944="` echo /root/.ansible/tmp/ansible-tmp-1559804568.97-125703572820944 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpARSeK3 TO /root/.ansible/tmp/ansible-tmp-1559804568.97-125703572820944/fortiosconfig.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1559804568.97-125703572820944/ /root/.ansible/tmp/ansible-tmp-1559804568.97-125703572820944/fortiosconfig.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1559804568.97-125703572820944/fortiosconfig.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1559804568.97-125703572820944/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_vnfoDB/ansible_module_fortiosconfig.py", line 946, in <module>
    main()
  File "/tmp/ansible_vnfoDB/ansible_module_fortiosconfig.py", line 934, in main
    module.params['action'])(module.params)
  File "/tmp/ansible_vnfoDB/ansible_module_fortiosconfig.py", line 569, in fortigate_set
    login(data)
  File "/tmp/ansible_vnfoDB/ansible_module_fortiosconfig.py", line 492, in login
    fos.login(host, username, password)
  File "/usr/lib/python2.7/site-packages/fortiosapi/fortiosapi.py", line 171, in login
    data='username=' + urllib.parse.quote(username) + '&secretkey=' + urllib.parse.quote(password) + "&ajax=1", timeout=self.timeout)
AttributeError: 'module' object has no attribute 'parse'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_vnfoDB/ansible_module_fortiosconfig.py\", line 946, in <module>\n    main()\n  File \"/tmp/ansible_vnfoDB/ansible_module_fortiosconfig.py\", line 934, in main\n    module.params['action'])(module.params)\n  File \"/tmp/ansible_vnfoDB/ansible_module_fortiosconfig.py\", line 569, in fortigate_set\n    login(data)\n  File \"/tmp/ansible_vnfoDB/ansible_module_fortiosconfig.py\", line 492, in login\n    fos.login(host, username, password)\n  File \"/usr/lib/python2.7/site-packages/fortiosapi/fortiosapi.py\", line 171, in login\n    data='username=' + urllib.parse.quote(username) + '&secretkey=' + urllib.parse.quote(password) + \"&ajax=1\", timeout=self.timeout)\nAttributeError: 'module' object has no attribute 'parse'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
	to retry, use: --limit @/home/jerry/40ansible/examples/fortigate_mix.retry

**Comment by jerrytoh123** [comment]
I suspect that my Ansible is pointing to the wrong python module, which python version should we be using for this module?

**Comment by mamunozgonzalez** [comment]
Hi @jerrytoh123 
well, in this case the error you are getting is because of old libraries in Python2. As you know Python2 will be "End of Maintenance" next December and no Python2 script will be maintained any more. Could you run Ansible with Python3? 

It is very simple with pip3:
```
pip3 install ansible
```
This will leave ansible binaries in ~/.local/bin and will ensure you run Python3 with Ansible, which is the recommended way.

**Comment by mamunozgonzalez** [comment]
I'm closing this ticket. If you still have the issue feel free to open it again.
Thanks.
