### ISSUE TITLE
backup config per vdom 

### ISSUE THREAD

**Issue by michael-heller** [fortinet-solutions-cse/40ansible#45]
hi there

so I'm trying to backup the fortigate configuration per vdom according your example here:
[fortios backup](https://github.com/fortinet-solutions-cse/40ansible/blob/master/examples/fortigate_backup_config.yml)

however, the configuration backed up is always the full configuration of the firewall and not the one of the corresponding vdom.
On the other hand if I set the vdom parameter to some non existing the playbook fails. so it looks like the parameter is checked but does not invoke the correct backup command.

Am I doing something wrong?

Thanks.

**Comment by mamunozgonzalez** [comment]
Hi @michael-heller 
At the moment the fortiosconfig backup feature only supports global backups to file (and not usb) as you can see in: https://github.com/fortinet-solutions-cse/40ansible/blob/e2a663dbd535671600e56d64ddc0c465b88991e4/library/fortiosconfig.py#L778

**Comment by michael-heller** [comment]
Thanks for the quick reply.
I have not seen this when I reviewed the current code.

Is it planned to introduce this feature?
otherwise I would remove the vdom parameter from the example.

**Comment by migumun** [comment]
@frankshen01 thanks a lot for the quick solution submitted. 
Since the PR is already merged, I'm closing this issue.
