### ISSUE TITLE
How to change SSH conection port.

### ISSUE THREAD

**Issue by kanom54** [fortinet-solutions-cse/40ansible#47]
Hello,

I have ssh customized ports for my Fortigates, im wondering if i could change that. On the playbooks examples doesnt specify.

Thanks you.
FS

**Comment by migumun** [comment]
Hi @kanom54 ,
 Do you want to change the ssh port configured in your FGT? 
If so, can you check if https://github.com/ansible/ansible/blob/98b6b98287436535f0dfc99ffe3333e5a196b9a3/lib/ansible/modules/network/fortios/fortios_system_global.py#L168 solves your issue? 
This module is already available in Ansible 2.9 and it was created and supported by Fortinet. The link points to the admin_ssh_port attribute that you can supposedly use to solve your issue with SSH.

If, on the oher hand, what you want to do is to use a custom port on the call to fortiosconfig, I'm afraid that it is not possible (unless you manually change the code in the library). Also, the ssh feature over ansible will be deprecated soon and is normally not recommended to be used. Now, all of the FGT features can be configured using the new modules available in 2.9.
